name: "TurboGrow"
version: "1.0.1"
slug: "turbogrow"
description: "Add-on para Home Assistant"
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
options: {}
schema: {}
map:
  - config:rw
