name: "TurboGrow"
version: "1.1.0"
slug: "turbogrow"
description: "mvp del addon para control de tareas"
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armv7
options: {}
schema: {}
map:
  - config:rw
