bot:
  token: "TU_TOKEN_DEL_BOT_AQUI"
  admin_id: 123456789
  usuarios:
    - id: 111111111
      nombre: "UsuarioUno"
    - id: 222222222
      nombre: "UsuarioDos"
ha:
  url: "http://tu-home-assistant.local:8123"
  token: "TU_TOKEN_DE_HA_AQUI"
