name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Se ejecuta cuando se sube código a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION | tr -d '\r\n')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            flyingcumbancha/turbomanu_testing:${{ env.VERSION }}
            flyingcumbancha/turbomanu_testing:latest